#!/bin/bash
set -Eeu -o pipefail
# An easy way to search for a file, either using the ``find`` command,
# or just grepping index.txt if it exists.
if [[ -f index.txt ]];
then
    cat index.txt | grep -i "$@"
else
    find . | grep -i "$@"
fi
