#!/usr/bin/env python
"""
Prints a range of integers to stdout delimited by newline. The range is
inclusive.
"""
import sys


def main(first, last):
    for i in xrange(first, last + 1):
        print(i)


if __name__ == "__main__":
    try:
        first, last = sys.argv[1], sys.argv[2]
    except IndexError:
        first, last = 1, sys.argv[1]
    first, last = int(first), int(last)
    main(first, last)
