#!/usr/bin/env python
"""Trims leading and ending whitespace from stdin and prints to stdout."""
import fileinput


def main():
    for line in fileinput.input():
        print(line.strip())


if __name__ == "__main__":
    main()
