#!/Users/chris/virtualenvs/env3/bin/python
"""
Script to speak text from stdin or from filenames given as arguments.

Installation:
    - Install python libraries:
    $ pip install gtts

    - Install mplayer to use --play option:
    $ brew install mplayer
"""
import argparse
import sys
import fileinput
import os

try:
    from gtts import gTTS
except ImportError:
    sys.exit("The gtts python library is required.")


def save(text, filename):
    recorder = gTTS(text=text, slow=False)  # , lang=language, slow=False)
    log(f"Saving {filename}...")
    recorder.save(filename)
    if args.play:
        log(f"Playing {filename}...")
        speed_factor = 1.5
        command = f"mplayer -noar -af scaletempo -speed {speed_factor} {filename}"
        if args.verbose:
            os.system(f"{command}")
        else:
            os.system(f"{command} > /dev/null")


def main():
    files = [args.filename] if args.filename else []
    text = [line.strip() for line in fileinput.input(files=files) if line.strip()]
    text = "\n".join(text)
    filename = "stdin.mp3" if not args.filename else args.filename + ".mp3"
    if args.sample:
        text = text[:400]
    save(text, filename)


def log(text):
    if args.verbose:
        print(text)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename", nargs="?", help="source text file")
    parser.add_argument(
        "--verbose", action="store_true", help="don't print result to stdout"
    )
    parser.add_argument(
        "--play", action="store_true", help="play the resulting file immediately"
    )
    parser.add_argument(
        "--sample",
        action="store_true",
        help="only convert a small sample (mostly for debugging)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    main()
