#!/Users/chris/virtualenvs/env3/bin/python
"""
Script to speak text from stdin or from filenames given as arguments.

Installation:
    - Install python libraries:
    $ pip install gtts pydub

    - Install mplayer to use --play option:
    $ brew install mplayer
"""
import argparse
import sys
import fileinput
import os

try:
    from gtts import gTTS
except ImportError:
    sys.exit("The gtts python library is required.")

try:
    import pydub
    import pydub.playback
except ImportError:
    sys.exit("The pydub python library is required.")


def save(text, filename):
    recorder = gTTS(text=text, slow=False)  # , lang=language, slow=False)
    log(f"Saving {filename}...")
    recorder.save(filename)
    if args.use_pydub:
        log(f"Speeding up {filename}...")
        seg = pydub.AudioSegment.from_file(filename)
        seg = seg.speedup(args.speedup)
        log(f"Resaving {filename}...")
        seg.export(filename)
    if args.play:
        log(f"Playing {filename}...")
        if args.use_pydub:
            pydub.playback.play(seg)
            return
        command = f"mplayer -noar -af scaletempo -speed {args.speedup} {filename}"
        if args.verbose:
            os.system(f"{command}")
        else:
            os.system(f"{command} > /dev/null")


def main():
    files = [args.filename] if args.filename else []
    text = [line.strip() for line in fileinput.input(files=files) if line.strip()]
    text = "\n".join(text)
    filename = "stdin.mp3" if not args.filename else args.filename + ".mp3"
    if args.sample:
        text = text[:400]
    save(text, filename)


def log(text):
    if args.verbose:
        print(text)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("filename", nargs="?", help="source text file")
    parser.add_argument(
        "--verbose", action="store_true", help="don't print result to stdout"
    )
    parser.add_argument(
        "--speedup", type=float, default=1.5, help="speedup factor"
    )
    parser.add_argument(
        "--play", action="store_true", help="play the resulting file immediately"
    )
    parser.add_argument(
        "--use-pydub", action="store_true", help="speedup with pydub instead of mplayer"
    )
    parser.add_argument(
        "--sample",
        action="store_true",
        help="only convert a small sample (mostly for debugging)",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    main()
