#!/usr/bin/env python3

import argparse
import atexit
import subprocess
import os
import shutil


def main():
    parser = argparse.ArgumentParser(description="Process YouTube audio.")
    parser.add_argument("url", help="YouTube URL")
    parser.add_argument("start_time", help="Start time in HH:MM:SS format")
    parser.add_argument("end_time", help="End time in HH:MM:SS format")

    args = parser.parse_args()

    original_data = "/tmp/youtube-audio-cut-{}.original.mp3".format(os.getpid())
    cut_data = "/tmp/youtube-audio-cut-{}.cut.mp3".format(os.getpid())

    # Download the YouTube video as an audio file
    download_cmd = [
        "youtube-dl",
        "-o",
        original_data,
        "-x",
        "--audio-format",
        "mp3",
        "--audio-quality",
        "0",  # highest
        args.url,
    ]
    subprocess.run(download_cmd, check=True)

    # Use ffmpeg to cut the audio file
    ffmpeg_cmd = [
        "ffmpeg",
        "-i",
        original_data,
        "-ss",
        args.start_time,
        "-to",
        args.end_time,
        cut_data,
    ]
    subprocess.run(ffmpeg_cmd, check=True)

    # Move the audio file to the current directory
    destination = os.getcwd() + "/audio-capture-cut.mp3"
    shutil.move(cut_data, destination)
    print(f"Audio file saved to {destination}")
    cleanup()


def cleanup():
    # Delete temporary files if they exist
    if os.path.exists(original_data):
        os.remove(original_data)

    if os.path.exists(cut_data):
        os.remove(cut_data)


if __name__ == "__main__":
    main()
